package models

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

type Tool struct {
	Definition mcp.Tool
	Handler    func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error)
}

// RecipientAccountReference represents the RecipientAccountReference schema from the OpenAPI specification
type RecipientAccountReference struct {
	Referenceid string `json:"referenceId,omitempty"` // <span class="tablenote"><b>Note</b>: DO NOT USE THIS FIELD. eBay now controls all electronic payment methods available for a marketplace, and a seller never has to specify any electronic payment methods.</span>
	Referencetype string `json:"referenceType,omitempty"` // <span class="tablenote"><b>Note</b>: DO NOT USE THIS FIELD. eBay now controls all electronic payment methods available for a marketplace, and a seller never has to specify any electronic payment methods.</span> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:RecipientAccountReferenceTypeEnum'>eBay API documentation</a>
}

// RateTable represents the RateTable schema from the OpenAPI specification
type RateTable struct {
	Countrycode string `json:"countryCode,omitempty"` // A two-letter <a href="https://www.iso.org/iso-3166-country-codes.html " title="https://www.iso.org " target="_blank">ISO 3166</a> country code representing the eBay marketplace where the shipping rate table is defined. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:CountryCodeEnum'>eBay API documentation</a>
	Locality string `json:"locality,omitempty"` // This enumeration value returned here indicates whether the shipping rate table is a domestic or international shipping rate table. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ShippingOptionTypeEnum'>eBay API documentation</a>
	Name string `json:"name,omitempty"` // The seller-defined name for the shipping rate table.
	Ratetableid string `json:"rateTableId,omitempty"` // A unique eBay-assigned ID for a seller's shipping rate table. These <b>rateTableId</b> values are used to associate shipping rate tables to fulfillment business policies or directly to listings through an add/revise/relist call in the Trading API.
}

// PaymentMethod represents the PaymentMethod schema from the OpenAPI specification
type PaymentMethod struct {
	Brands []string `json:"brands,omitempty"` // <span class="tablenote"><b>Note</b>: This array is no longer applicable and should not be used. eBay now controls all electronic payment methods available for a marketplace, and a seller never has to specify any electronic payment methods, including any credit card brands accepted. </span>
	Paymentmethodtype string `json:"paymentMethodType,omitempty"` // eBay now controls all electronic payment methods available for a marketplace, so only offline payment method enum values may be used in this field, and offline payment methods will only be applicable to listings that require or support offline payments. See the <b>PaymentMethodTypeEnum</b> type for supported offline payment method enum values. </p> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentMethodTypeEnum'>eBay API documentation</a>
	Recipientaccountreference RecipientAccountReference `json:"recipientAccountReference,omitempty"` // <span class="tablenote"><b>Note</b>: This type is no longer applicable. eBay now controls all electronic payment methods available for a marketplace, and a seller never has to specify any electronic payment methods.</span>
}

// ReturnPolicy represents the ReturnPolicy schema from the OpenAPI specification
type ReturnPolicy struct {
	Returnshippingcostpayer string `json:"returnShippingCostPayer,omitempty"` // This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either <code>BUYER</code> or <code>SELLER</code>. <br/><br/>Depending on the return policy and specifics of the return, either the buyer or the seller can be responsible for the return shipping costs. Note that the seller is always responsible for return shipping costs for SNAD-related issues. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum'>eBay API documentation</a>
	Returnsaccepted bool `json:"returnsAccepted,omitempty"` // If this field is returned as <code>true</code>, the seller accepts returns. <br/><br/><span class="tablenote"><strong>Note:</strong>Top-Rated sellers must accept item returns and the <b>handlingTime</b> should be set to zero days or one day for a listing to receive a Top-Rated Plus badge on the View Item or search result pages. For more information on eBay's Top-Rated seller program, see <a href="https://pages.ebay.com/help/sell/top-rated.html ">Becoming a Top Rated Seller and qualifying for Top Rated Plus benefits</a>.</span>
	Internationaloverride InternationalReturnOverrideType `json:"internationalOverride,omitempty"` // This type defines the fields for a seller's international return policy. Sellers have the ability to set separate domestic and international return policies, but if an international return policy is not set, the same return policy settings specified for the domestic return policy are also used for returns for international buyers.
	Returnmethod string `json:"returnMethod,omitempty"` // This field is only returned if the seller is willing to offer a replacement item as an alternative to 'Money Back'. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum'>eBay API documentation</a>
	Description string `json:"description,omitempty"` // A seller-defined description of the return business policy. This description is only for the seller's use, and is not exposed on any eBay pages. <br/><br/><b>Max length</b>: 250
	Name string `json:"name,omitempty"` // A seller-defined name for this payment business policy. Names must be unique for policies assigned to the same marketplace.<br /><br /><b>Max length:</b> 64
	Refundmethod string `json:"refundMethod,omitempty"` // If a seller indicates that they will accept buyer returns, this value will be set to <code>MONEY_BACK</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:RefundMethodEnum'>eBay API documentation</a>
	Restockingfeepercentage string `json:"restockingFeePercentage,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer allows sellers to charge a restocking fee for buyer remorse returns. If this field is included, it is ignored and it is no longer returned.</p>
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates which category group that the return policy applies to.<br/><br/><span class="tablenote"><b>Note</b>: Return business policies are not applicable to motor vehicle listings, so the <b>categoryTypes.name</b> value will always be <code>ALL_EXCLUDING_MOTORS_VEHICLES</code> for return business policies.</span>
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this return business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Returninstructions string `json:"returnInstructions,omitempty"` // This text-based field provides more details on seller-specified return instructions. This field is only returned if set for the return business policy. <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is no longer supported on many eBay marketplaces. To see if a marketplace and eBay category does support this field, call <a href="/api-docs/sell/metadata/resources/marketplace/methods/getReturnPolicies">getReturnPolicies</a> method of the <b>Metadata API</b>. Then you will look for the <b>policyDescriptionEnabled</b> field with a value of <code>true</code> for the eBay category.</span></p><br/><b>Max length</b>: 5000 (8000 for DE)
	Returnpolicyid string `json:"returnPolicyId,omitempty"` // A unique eBay-assigned ID for a return business policy. This ID is generated when the policy is created.
	Extendedholidayreturnsoffered bool `json:"extendedHolidayReturnsOffered,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer supports extended holiday returns. Any value supplied in this field is neither read nor returned.</p>
	Returnperiod TimeDuration `json:"returnPeriod,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
}

// SalesTaxes represents the SalesTaxes schema from the OpenAPI specification
type SalesTaxes struct {
	Salestaxes []SalesTax `json:"salesTaxes,omitempty"` // An array of one or more sales tax rate entries for a specific marketplace (or all applicable marketplaces if the <b>country_code</b> query parameter is not used.<br><br>If no sales tax rate entries are set up, no response payload is returned, but only an HTTP status code of <code>204 No Content</code>.
}

// PaymentsProgramOnboardingSteps represents the PaymentsProgramOnboardingSteps schema from the OpenAPI specification
type PaymentsProgramOnboardingSteps struct {
	Status string `json:"status,omitempty"` // This enumeration value indicates the status of the associated step. <p> <span class="tablenote"><strong>Note:</strong> Only one step can be <code>IN_PROGRESS</code> at a time.</span></p> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentsProgramOnboardingStepStatus'>eBay API documentation</a>
	Weburl string `json:"webUrl,omitempty"` // This URL provides access to the <code>IN_PROGRESS</code> step.
	Name string `json:"name,omitempty"` // The name of the step in the steps array. Over time, these names are subject to change as processes change. The output sample contains example step names. Review an actual call response for updated step names.
}

// PaymentPolicyResponse represents the PaymentPolicyResponse schema from the OpenAPI specification
type PaymentPolicyResponse struct {
	Prev string `json:"prev,omitempty"` // This field is for future use.
	Total int `json:"total,omitempty"` // The total number of payment business policies retrieved in the result set. <br/><br/>If no payment business policies are defined for the specified marketplace, this field is returned with a value of <code>0</code>.
	Href string `json:"href,omitempty"` // This field is for future use.
	Limit int `json:"limit,omitempty"` // This field is for future use.
	Next string `json:"next,omitempty"` // This field is for future use.
	Offset int `json:"offset,omitempty"` // This field is for future use.
	Paymentpolicies []PaymentPolicy `json:"paymentPolicies,omitempty"` // A list of all of the seller's payment business policies defined for the specified marketplace. This array will be returned as empty if no payment business policies are defined for the specified marketplace.
}

// ShippingOption represents the ShippingOption schema from the OpenAPI specification
type ShippingOption struct {
	Packagehandlingcost Amount `json:"packageHandlingCost,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Insuranceoffered bool `json:"insuranceOffered,omitempty"` // This field has been deprecated. <br/><br/>Shipping insurance is offered only via a shipping carrier's shipping services and is no longer available via eBay shipping policies.
	Optiontype string `json:"optionType,omitempty"` // This field is used to indicate if the corresponding shipping service options (under <b>shippingServices</b> array) are domestic or international shipping service options. This field is conditionally required if any shipping service options are specified (domestic and/or international). For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ShippingOptionTypeEnum'>eBay API documentation</a>
	Ratetableid string `json:"rateTableId,omitempty"` // This field is used if the seller wants to associate a domestic or international shipping rate table to the fulfillment business policy. The <a href="/api-docs/sell/account/resources/rate_table/methods/getRateTables">getRateTables</a> method can be used to retrieve shipping rate table IDs.<br/><br/>With domestic and international shipping rate tables, the seller can set different shipping costs based on shipping regions and shipping speed/level of service (one-day, expedited, standard, economy). There are also options to additional per-weight and handling charges.<br/><br/>Sellers need to be careful that shipping rate tables match the corresponding shipping service options. In other words, a domestic shipping rate table must not be specified in the same container where international shipping service options are being specified, and vice versa, and the shipping speed/level of service of the provided shipping service options should match the shipping speed/level of service options that are defined in the shipping rate tables. <br /><br />For example, if the corresponding shipping rate table defines costs for one-day shipping services, there should be at least one one-day shipping service option specified under the <b>shippingServices</b> array.<br/><br/>This field is returned if set.
	Shippingpromotionoffered bool `json:"shippingPromotionOffered,omitempty"` // This boolean indicates whether or not the seller has set up a promotional shipping discount that will be available to buyers who satisfy the requirements of the shipping discount rule. <br/><br/>The seller can create and manage shipping promotional discounts using (Get/Set) <b>ShippingDiscountProfiles</b> calls in the <b>Trading API</b> or through the <b>Shipping Preferences</b> in <b>My eBay</b>. <br/><br/><span class="tablenote"><b>Note: </b>Initially, shipping discount profiles in the <b>Account API</b> will <i>not</i> be available to all sellers.</span>
	Shippingdiscountprofileid string `json:"shippingDiscountProfileId,omitempty"` // This field is the unique identifier of a seller's domestic or international shipping discount profile. If a buyer satisfies the requirements of the discount rule, this buyer will receive a shipping discount for the order. <br /><br />The seller can create and manage shipping discount profiles using (Get/Set) <b>ShippingDiscountProfiles</b> calls in the <b>Trading API</b> or through the <b>Shipping Preferences</b> in <b>My eBay</b>. <br/><br/><span class="tablenote"><b>Note: </b>Initially, shipping discount profiles in the <b>Account API</b> will <i>not</i> be available to all sellers.</span>
	Shippingservices []ShippingService `json:"shippingServices,omitempty"` // This array consists of the domestic or international shipping services options that are defined for the policy. The shipping service options defined under this array should match what is set in the corresponding <b>shippingOptions.optionType</b> field (which controls whether domestic or international shipping service options are being defined). If a shipping rate table is being used, the specified shipping service options should also match the shipping rate table settings (domestic or international, shipping speed/level of service, etc.) <br/><br/>Sellers can specify up to four domestic shipping services and up to five international shipping service options by using separate <b>shippingService</b> containers for each. If the seller is using the Global Shipping Program as an international option, only a total of four international shipping service options (including GSP) can be offered. <br/><br/> See <a href="/api-docs/sell/static/seller-accounts/ht_shipping-setting-shipping-carrier-and-service-values.html" target="_blank">How to set up shipping carrier and shipping service values</a>. <br /><br />To use the eBay standard envelope service (eSE), see <a href="/api-docs/sell/static/seller-accounts/using-the-ebay-standard-envelope-service.html" target="_blank">Using eBay standard envelope (eSE) service</a>.<br /><br />This array is conditionally required if the seller is offering one or more domestic and/or international shipping service options.
	Costtype string `json:"costType,omitempty"` // This field defines whether the shipping cost model is <code>FLAT_RATE</code> (the same rate for all buyers, or buyers within a region if shipping rate tables are used) or <code>CALCULATED</code> (the shipping rate varies by the ship-to location and size and weight of the package). <br/><br/>This field is conditionally required if any shipping service options are specified (domestic and/or international). For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ShippingCostTypeEnum'>eBay API documentation</a>
	Insurancefee Amount `json:"insuranceFee,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
}

// ReturnPolicyRequest represents the ReturnPolicyRequest schema from the OpenAPI specification
type ReturnPolicyRequest struct {
	Internationaloverride InternationalReturnOverrideType `json:"internationalOverride,omitempty"` // This type defines the fields for a seller's international return policy. Sellers have the ability to set separate domestic and international return policies, but if an international return policy is not set, the same return policy settings specified for the domestic return policy are also used for returns for international buyers.
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this return business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Returnsaccepted bool `json:"returnsAccepted,omitempty"` // If set to <code>true</code>, the seller accepts returns. <p><span class="tablenote"><strong>Note:</strong>Top-Rated sellers must accept item returns and the <b>handlingTime</b> should be set to zero days or one day for a listing to receive a Top-Rated Plus badge on the View Item or search result pages. For more information on eBay's Top-Rated seller program, see <a href="http://pages.ebay.com/help/sell/top-rated.html ">Becoming a Top Rated Seller and qualifying for Top Rated Plus benefits</a>.</span></p>
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates which category group that the return policy applies to.<br/><br/><span class="tablenote"><b>Note</b>: Return business policies are not applicable to motor vehicle listings, so the <b>categoryTypes.name</b> value must be set to <code>ALL_EXCLUDING_MOTORS_VEHICLES</code> for return business policies.</span>
	Refundmethod string `json:"refundMethod,omitempty"` // This value indicates the refund method that will be used by the seller for buyer returns.<p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> If this field is not included in a return business policy, it will default to MONEY_BACK.</p> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:RefundMethodEnum'>eBay API documentation</a>
	Returninstructions string `json:"returnInstructions,omitempty"` // This text-based field provides more details on seller-specified return instructions. <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is no longer supported on many eBay marketplaces. To see if a marketplace and eBay category does support this field, call <a href="/api-docs/sell/metadata/resources/marketplace/methods/getReturnPolicies">getReturnPolicies</a> method of the <b>Metadata API</b>. Then you will look for the <b>policyDescriptionEnabled</b> field with a value of <code>true</code> for the eBay category.</span></p><br/><b>Max length</b>: 5000 (8000 for DE)
	Name string `json:"name,omitempty"` // A seller-defined name for this return business policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64
	Restockingfeepercentage string `json:"restockingFeePercentage,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer allows sellers to charge a restocking fee for buyer remorse returns. If this field is included, it is ignored.</p>
	Returnmethod string `json:"returnMethod,omitempty"` // This field can be used if the seller is willing and able to offer a replacement item as an alternative to 'Money Back'. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum'>eBay API documentation</a>
	Returnperiod TimeDuration `json:"returnPeriod,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Returnshippingcostpayer string `json:"returnShippingCostPayer,omitempty"` // This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either <code>BUYER</code> or <code>SELLER</code>. <br/><br/>Depending on the return policy and specifics of the return, either the buyer or the seller can be responsible for the return shipping costs. Note that the seller is always responsible for return shipping costs for SNAD-related issues. <br/><br/>This field is conditionally required if <b>returnsAccepted</b> is set to <code>true</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum'>eBay API documentation</a>
	Description string `json:"description,omitempty"` // A seller-defined description of the return business policy. This description is only for the seller's use, and is not exposed on any eBay pages. <br/><br/><b>Max length</b>: 250
	Extendedholidayreturnsoffered bool `json:"extendedHolidayReturnsOffered,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer supports extended holiday returns. Any value supplied in this field is neither read nor returned.</p>
}

// FulfillmentPolicy represents the FulfillmentPolicy schema from the OpenAPI specification
type FulfillmentPolicy struct {
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates whether the fulfillment policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Name string `json:"name,omitempty"` // A seller-defined name for this fulfillment policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64
	Freightshipping bool `json:"freightShipping,omitempty"` // If returned as <code>true</code>, the seller offers freight shipping. Freight shipping can be used for large items over 150 lbs.
	Globalshipping bool `json:"globalShipping,omitempty"` // If returned as <code>true</code>, eBay's Global Shipping Program will be used by the seller to ship items to international locations.<br /><br /><span class="tablenote"><b>Note</b>: On the US marketplace, the <em><b>Global Shipping Program</b></em> is scheduled to be replaced by a new intermediated international shipping program called <em><b>eBay International Shipping</b></em>. US sellers who are opted in to the Global Shipping Program will be automatically opted in to eBay International Shipping when it becomes available to them. All US sellers will be migrated by March 31, 2023. <br /><br />eBay International Shipping is an account level setting, and no field needs to be set in a Fulfillment business policy to enable it. As long as the US seller's account is opted in to eBay International Shipping, this shipping option will be enabled automatically for all listings where international shipping is available. <br /><br />A US seller who is opted in to eBay International Shipping can also specify individual international shipping service options for a Fulfillment business policy.</span>
	Handlingtime TimeDuration `json:"handlingTime,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Shippingoptions []ShippingOption `json:"shippingOptions,omitempty"` // This array is used to provide detailed information on the domestic and international shipping options available for the policy. A separate <b>ShippingOption</b> object covers domestic shipping service options and international shipping service options (if the seller ships to international locations). <br /><br />The <b>optionType</b> field indicates whether the <b>ShippingOption</b> object applies to domestic or international shipping, and the <b>costType</b> field indicates whether flat-rate shipping or calculated shipping will be used. <p>A separate <b>ShippingServices</b> object is used to specify cost and other details for every available domestic and international shipping service option. </p>
	Description string `json:"description,omitempty"` // A seller-defined description of the fulfillment policy. This description is only for the seller's use, and is not exposed on any eBay pages. This field is returned if set for the policy. <br/><br/><b>Max length</b>: 250
	Fulfillmentpolicyid string `json:"fulfillmentPolicyId,omitempty"` // A unique eBay-assigned ID for the fulfillment policy. This ID is generated when the policy is created.
	Localpickup bool `json:"localPickup,omitempty"` // If returned as <code>true</code>, local pickup is available for this policy.
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this fulfillment policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Pickupdropoff bool `json:"pickupDropOff,omitempty"` // If returned as <code>true</code>, the seller offers the "Click and Collect" option. <br/><br/>Currently, "Click and Collect" is available only to large retail merchants the eBay AU and UK marketplaces.
	Shiptolocations RegionSet `json:"shipToLocations,omitempty"` // This type consists of the <b>regionIncluded</b> and <b>regionExcluded</b> arrays, which indicate the areas to where the seller does and doesn't ship.
}

// RegionSet represents the RegionSet schema from the OpenAPI specification
type RegionSet struct {
	Regionexcluded []Region `json:"regionExcluded,omitempty"` // An array of one or more <b>regionName</b> values that specify the areas to where a seller does not ship. A <b>regionExcluded</b> list should only be set in the top-level <b>shipToLocations</b> container and not within the <b>shippingServices.shipToLocations</b> container used to specify which shipping regions are serviced by each available shipping service option. <p>Many sellers are willing to ship to many international locations, but they may want to exclude some world regions or some countries as places they are willing to ship to.<br/><br/>This array will be returned as empty if no shipping regions are excluded with the fulfillment business policy.<br /> <br /><span class="tablenote"><b>Note: </b> The <b>regionExcluded</b> array is not applicable for motor vehicle business policies on the US, CA, or UK marketplaces. If this array is used in a <b>createFulfillmentPolicy</b> or <b>updateFulfillmentPolicy</b> request, it will be ignored.</span>
	Regionincluded []Region `json:"regionIncluded,omitempty"` // An array of one or more <b>regionName</b> fields that specify the areas to where a seller ships. <br />Each eBay marketplace supports its own set of allowable shipping locations.<br /> <br /><span class="tablenote"><b>Note: </b> The <b>regionIncluded</b> array is not applicable for motor vehicle business policies on the US, CA, or UK marketplaces. If this array is used in a <b>createFulfillmentPolicy</b> or <b>updateFulfillmentPolicy</b> request, it will be ignored.</span>
}

// SalesTax represents the SalesTax schema from the OpenAPI specification
type SalesTax struct {
	Salestaxpercentage string `json:"salesTaxPercentage,omitempty"` // The sales tax rate that will be applied to sales price. The <b>shippingAndHandlingTaxed</b> value will indicate whether or not sales tax is also applied to shipping and handling charges<br><br>Although it is a string, a percentage value is returned here, such as <code>7.75</code>
	Shippingandhandlingtaxed bool `json:"shippingAndHandlingTaxed,omitempty"` // If returned as <code>true</code>, sales tax is also applied to shipping and handling charges, and not just the total sales price of the order.
	Countrycode string `json:"countryCode,omitempty"` // The country code enumeration value identifies the country to which this sales tax rate applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:CountryCodeEnum'>eBay API documentation</a>
	Salestaxjurisdictionid string `json:"salesTaxJurisdictionId,omitempty"` // A unique ID that identifies the sales tax jurisdiction to which the sales tax rate applies (for example, a state within the United States).
}

// SellingLimit represents the SellingLimit schema from the OpenAPI specification
type SellingLimit struct {
	Amount Amount `json:"amount,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Quantity int `json:"quantity,omitempty"` // This field shows the monthly cap for total quantity sold allowed for the seller's account. This container may not be returned if a seller does not have a monthly cap for total quantity sold.
}

// KycResponse represents the KycResponse schema from the OpenAPI specification
type KycResponse struct {
	Kycchecks []KycCheck `json:"kycChecks,omitempty"` // This array contains one or more KYC checks required from a managed payments seller. The seller may need to provide more documentation and/or information about themselves, their company, or the bank account they are using for seller payouts.<br/><br/>If no KYC checks are currently required from the seller, this array is not returned, and the seller only receives a <code>204 No Content</code> HTTP status code.
}

// Region represents the Region schema from the OpenAPI specification
type Region struct {
	Regionname string `json:"regionName,omitempty"` // A string that indicates the name of a region, as defined by eBay. A "region" can be either a 'world region' (e.g., the "Middle East" or "Southeast Asia"), a country (represented with a two-letter country code), a state or province (represented with a two-letter code), or a special domestic region within a country. <br /><br />The <b>GeteBayDetails</b> call in the Trading API can be used to retrieve the world regions and special domestic regions within a specific country. To get these enumeration values, call <b>GeteBayDetails</b> with the <b>DetailName</b> value set to <b>ExcludeShippingLocationDetails</b>.
	Regiontype string `json:"regionType,omitempty"` // Reserved for future use. <!--The region's type, which can be one of the following: 'COUNTRY', 'COUNTRY_REGION', 'STATE_OR_PROVINCE', 'WORLD_REGION', or 'WORLDWIDE'.--> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:RegionTypeEnum'>eBay API documentation</a>
}

// Amount represents the Amount schema from the OpenAPI specification
type Amount struct {
	Value string `json:"value,omitempty"` // The monetary amount in the specified <b>currency</b>.
	Currency string `json:"currency,omitempty"` // The base currency applied to the <b>value</b> field to establish a monetary amount. <br/><br/>The currency is represented as a 3-letter <a href="https://www.iso.org/iso-4217-currency-codes.html " title="https://www.iso.org " target="_blank">ISO 4217</a> currency code. For example, the code for the Canadian Dollar is <code>CAD</code>.<br/><br/><b>Default:</b> The default currency of the eBay marketplace that hosts the listing. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:CurrencyCodeEnum'>eBay API documentation</a>
}

// SalesTaxBase represents the SalesTaxBase schema from the OpenAPI specification
type SalesTaxBase struct {
	Shippingandhandlingtaxed bool `json:"shippingAndHandlingTaxed,omitempty"` // This field is set to <code>true</code> if the seller wishes to apply sales tax to shipping and handling charges, and not just the total sales price of the order. Otherwise, this field's value should be set to <code>false</code>.
	Salestaxpercentage string `json:"salesTaxPercentage,omitempty"` // This field is used to set the sales tax rate for the tax jurisdiction set in the call URI. When applicable to an order, this sales tax rate will be applied to sales price. The <b>shippingAndHandlingTaxed</b> value will indicate whether or not sales tax is also applied to shipping and handling charges<br><br>Although it is a string, a percentage value is set here, such as <code>7.75</code>.
}

// SellerEligibilityResponse represents the SellerEligibilityResponse schema from the OpenAPI specification
type SellerEligibilityResponse struct {
	Programtype string `json:"programType,omitempty"` // The eBay advertising program for which a seller may be eligible. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/plser:AdvertisingProgramEnum'>eBay API documentation</a>
	Reason string `json:"reason,omitempty"` // The reason why a seller is ineligible for the specified eBay advertising program.<br /><br />This field is only returned if the seller is ineligible for the eBay advertising program. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/plser:SellerIneligibleReasonEnum'>eBay API documentation</a>
	Status string `json:"status,omitempty"` // The seller elibibilty status for the specified eBay advertising program. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/cmlib:SellerEligibilityEnum'>eBay API documentation</a>
}

// CustomPolicyResponse represents the CustomPolicyResponse schema from the OpenAPI specification
type CustomPolicyResponse struct {
	Limit int `json:"limit,omitempty"` // <i>This field is for future use.</i>
	Next string `json:"next,omitempty"` // <i>This field is for future use.</i>
	Offset int `json:"offset,omitempty"` // <i>This field is for future use.</i>
	Prev string `json:"prev,omitempty"` // <i>This field is for future use.</i>
	Total int `json:"total,omitempty"` // <i>This field is for future use.</i>
	Custompolicies []CompactCustomPolicyResponse `json:"customPolicies,omitempty"` // This array contains the custom policies that match the input criteria.
	Href string `json:"href,omitempty"` // <i>This field is for future use.</i>
}

// CustomPolicyRequest represents the CustomPolicyRequest schema from the OpenAPI specification
type CustomPolicyRequest struct {
	Description string `json:"description,omitempty"` // Details of the seller's specific policy and terms for this policy.<br/><br/><b>Max length:</b> 15,000
	Label string `json:"label,omitempty"` // Customer-facing label shown on View Item pages for items to which the policy applies. This seller-defined string is displayed as a system-generated hyperlink pointing to detailed policy information.<br/><br/><b>Max length:</b> 65
	Name string `json:"name,omitempty"` // The seller-defined name for the custom policy. Names must be unique for policies assigned to the same seller, policy type, and eBay marketplace.<br /><span class="tablenote"><strong>Note:</strong> This field is visible only to the seller. </span><br/><br/><b>Max length:</b> 65
}

// ReturnPolicyResponse represents the ReturnPolicyResponse schema from the OpenAPI specification
type ReturnPolicyResponse struct {
	Next string `json:"next,omitempty"` // This field is for future use.
	Offset int `json:"offset,omitempty"` // This field is for future use.
	Prev string `json:"prev,omitempty"` // This field is for future use.
	Returnpolicies []ReturnPolicy `json:"returnPolicies,omitempty"` // A list of all of the seller's return business policies defined for the specified marketplace. This array will be returned as empty if no return business policies are defined for the specified marketplace.
	Total int `json:"total,omitempty"` // The total number of return business policies retrieved in the result set. <br/><br/>If no return business policies are defined for the specified marketplace, this field is returned with a value of <code>0</code>.
	Href string `json:"href,omitempty"` // This field is for future use.
	Limit int `json:"limit,omitempty"` // This field is for future use.
}

// PaymentsProgramResponse represents the PaymentsProgramResponse schema from the OpenAPI specification
type PaymentsProgramResponse struct {
	Status string `json:"status,omitempty"` // The enumeration value returned in this field indicates whether or not the seller's account is enabled for the payments program. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentsProgramStatus'>eBay API documentation</a>
	Waspreviouslyoptedin bool `json:"wasPreviouslyOptedIn,omitempty"` // If returned as <code>true</code>, the seller was at one point opted-in to the associated payment program, but they later opted out of the program. A value of <code>false</code> indicates the seller never opted-in to the program or if they did opt-in to the program, they never opted-out of it. <br><br>It's important to note that the setting of this field does not indicate the seller's current status regarding the payment program. It is possible for this field to return <code>true</code> while the <b>status</b> field returns <code>OPTED_IN</code>.
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which the payment program applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Paymentsprogramtype string `json:"paymentsProgramType,omitempty"` // This parameter specifies the payment program whose status is returned by the call. <br><br>Currently the only supported payments program is <code>EBAY_PAYMENTS</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentsProgramType'>eBay API documentation</a>
}

// RateTableResponse represents the RateTableResponse schema from the OpenAPI specification
type RateTableResponse struct {
	Ratetables []RateTable `json:"rateTables,omitempty"` // An array of all shipping rate tables defined for a marketplace (or all marketplaces if no <b>country_code</b> query parameter is used). This array will be returned as empty if the seller has no defined shipping rate tables for the specified marketplace.
}

// CompactCustomPolicyResponse represents the CompactCustomPolicyResponse schema from the OpenAPI specification
type CompactCustomPolicyResponse struct {
	Custompolicyid string `json:"customPolicyId,omitempty"` // The unique custom policy identifier for the policy being returned.<br/><br/><span class="tablenote"><strong>Note:</strong> This value is automatically assigned by the system when the policy is created.</span>
	Label string `json:"label,omitempty"` // Customer-facing label shown on View Item pages for items to which the policy applies. This seller-defined string is displayed as a system-generated hyperlink pointing to detailed policy information.<br/><br/><b>Max length:</b> 65
	Name string `json:"name,omitempty"` // The seller-defined name for the custom policy. Names must be unique for policies assigned to the same seller, policy type, and eBay marketplace.<br /><span class="tablenote"><strong>Note:</strong> This field is visible only to the seller. </span><br /><br /><b>Max length:</b> 65
	Policytype string `json:"policyType,omitempty"` // Specifies the type of Custom Policy being returned. <br/><br/>Two Custom Policy types are supported: <ul><li>Product Compliance (PRODUCT_COMPLIANCE)</li> <li>Takeback (TAKE_BACK)</li></ul> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:CustomPolicyTypeEnum'>eBay API documentation</a>
}

// SubscriptionResponse represents the SubscriptionResponse schema from the OpenAPI specification
type SubscriptionResponse struct {
	Href string `json:"href,omitempty"` // This field is for future use.
	Limit int `json:"limit,omitempty"` // This field is for future use.
	Next string `json:"next,omitempty"` // This field is for future use.
	Subscriptions []Subscription `json:"subscriptions,omitempty"` // An array of subscriptions associated with the seller account.
	Total int `json:"total,omitempty"` // The total number of subscriptions displayed on the current page of results.
}

// Programs represents the Programs schema from the OpenAPI specification
type Programs struct {
	Programs []Program `json:"programs,omitempty"` // An array of seller programs that the seller's account is opted in to.
}

// CategoryType represents the CategoryType schema from the OpenAPI specification
type CategoryType struct {
	DefaultField bool `json:"default,omitempty"` // <span class="tablenote"><strong>Note:</strong> This field has been deprecated and is no longer used.<ul><li>Do not include this field in any <b>create</b> or <b>update</b> method.</li><li>This field may be returned within the payload of a <b>get</b> method, but it can be ignored.</li></ul></span>
	Name string `json:"name,omitempty"` // The category type to which the policy applies (motor vehicles or non-motor vehicles). <br /><br />The <code>MOTORS_VEHICLES</code> category type is not valid for return policies. eBay flows do not support the return of motor vehicles. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:CategoryTypeEnum'>eBay API documentation</a>
}

// CustomPolicyCreateRequest represents the CustomPolicyCreateRequest schema from the OpenAPI specification
type CustomPolicyCreateRequest struct {
	Description string `json:"description,omitempty"` // Details of the seller's specific policy and terms for this policy.<br/><br/><b>Max length:</b> 15,000
	Label string `json:"label,omitempty"` // Customer-facing label shown on View Item pages for items to which the policy applies. This seller-defined string is displayed as a system-generated hyperlink pointing to detailed policy information.<br/><br/><b>Max length:</b> 65
	Name string `json:"name,omitempty"` // The seller-defined name for the custom policy. Names must be unique for policies assigned to the same seller, policy type, and eBay marketplace.<br /><span class="tablenote"><strong>Note:</strong> This field is visible only to the seller. </span><br/><br/><b>Max length:</b> 65
	Policytype string `json:"policyType,omitempty"` // Specifies the type of custom policy being created. <br/><br/>Two Custom Policy types are supported: <ul><li>Product Compliance (PRODUCT_COMPLIANCE)</li> <li>Takeback (TAKE_BACK)</li></ul> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:CustomPolicyTypeEnum'>eBay API documentation</a>
}

// PaymentsProgramOnboardingResponse represents the PaymentsProgramOnboardingResponse schema from the OpenAPI specification
type PaymentsProgramOnboardingResponse struct {
	Onboardingstatus string `json:"onboardingStatus,omitempty"` // This enumeration value indicates the eligibility of payment onboarding for the registered site. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:PaymentsProgramOnboardingStatus'>eBay API documentation</a>
	Steps []PaymentsProgramOnboardingSteps `json:"steps,omitempty"` // An array of the active process steps for payment onboarding and the status of each step. This array includes the step <strong>name</strong>, step <strong>status</strong>, and a <strong>webUrl</strong> to the <code>IN_PROGRESS</code> step. The step names are returned in sequential order.
}

// Deposit represents the Deposit schema from the OpenAPI specification
type Deposit struct {
	Amount Amount `json:"amount,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Duein TimeDuration `json:"dueIn,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Paymentmethods []PaymentMethod `json:"paymentMethods,omitempty"` // This array is no longer applicable and should not be used since eBay now manages the electronic payment options available to buyers to pay the deposit.
}

// TimeDuration represents the TimeDuration schema from the OpenAPI specification
type TimeDuration struct {
	Unit string `json:"unit,omitempty"` // These enum values represent the time measurement unit, such as <code>DAY</code>. A span of time is defined when you apply the value specified in the <b>value</b> field to the value specified for <b>unit</b>. <br/><br/>See <b>TimeDurationUnitEnum</b> for a complete list of possible time-measurement units. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:TimeDurationUnitEnum'>eBay API documentation</a>
	Value int `json:"value,omitempty"` // An integer that represents an amount of time, as measured by the time-measurement unit specified in the <b>unit</b> field.
}

// FulfillmentPolicyRequest represents the FulfillmentPolicyRequest schema from the OpenAPI specification
type FulfillmentPolicyRequest struct {
	Freightshipping bool `json:"freightShipping,omitempty"` // This field is included and set to <code>true</code> if freight shipping is available for the item. Freight shipping can be used for large items over 150 lbs.<br/><br/><b>Default</b>: false
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this fulfillment policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container is used to specify whether the fulfillment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Description string `json:"description,omitempty"` // A seller-defined description of the fulfillment policy. This description is only for the seller's use, and is not exposed on any eBay pages. <br/><br/><b>Max length</b>: 250
	Name string `json:"name,omitempty"` // A seller-defined name for this fulfillment policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64
	Shiptolocations RegionSet `json:"shipToLocations,omitempty"` // This type consists of the <b>regionIncluded</b> and <b>regionExcluded</b> arrays, which indicate the areas to where the seller does and doesn't ship.
	Globalshipping bool `json:"globalShipping,omitempty"` // This field is included and set to <code>true</code> if the seller wants to use the Global Shipping Program for international shipments. See the <a href="https://pages.ebay.com/help/sell/shipping-globally.html ">Global Shipping Program</a> help topic for more details and requirements on the Global Shipping Program.<br/><br/>It is possible for a seller to use a combination of the Global Shipping Program and other international shipping services. <br/><br/>If this value is set to <code>false</code> or if the field is omitted, the seller is responsible for manually specifying individual international shipping services (if the seller ships internationally)., as described in <a href="https://developer.ebay.com/api-docs/sell/static/seller-accounts/ht_shipping-worldwide.html ">Setting up worldwide shipping</a>. <br/><br/>Sellers can opt in or out of the Global Shipping Program through the Shipping preferences in My eBay.<br /><br /><span class="tablenote"><b>Note</b>: On the US marketplace, the <em><b>Global Shipping Program</b></em> is scheduled to be replaced by a new intermediated international shipping program called <em><b>eBay International Shipping</b></em>. US sellers who are opted in to the Global Shipping Program will be automatically opted in to eBay International Shipping when it becomes available to them. All US sellers will be migrated by March 31, 2023. <br /><br />eBay International Shipping is an account level setting, and no field needs to be set in a Fulfillment business policy to enable it. As long as the US seller's account is opted in to eBay International Shipping, this shipping option will be enabled automatically for all listings where international shipping is available. <br /><br />A US seller who is opted in to eBay International Shipping can also specify individual international shipping service options for a Fulfillment business policy.</span><p><b>Default</b>: false</p>
	Handlingtime TimeDuration `json:"handlingTime,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Localpickup bool `json:"localPickup,omitempty"` // This field should be included and set to <code>true</code> if local pickup is one of the fulfillment options available to the buyer. It is possible for the seller to make local pickup and some shipping service options available to the buyer.<br/><br/>With local pickup, the buyer and seller make arrangements for pickup time and location.<br/><br/><b>Default</b>: <code>false</code>
	Pickupdropoff bool `json:"pickupDropOff,omitempty"` // This field should be included and set to <code>true</code> if the seller offers the "Click and Collect" feature for an item. <p>To enable "Click and Collect" on a listing, a seller must be eligible for Click and Collect. Currently, Click and Collect is available to only large retail merchants selling in the eBay AU and UK marketplaces.</p> <p>In addition to setting this field to <code>true</code>, the merchant must also do the following to enable the "Click and Collect" option on a listing: <ul><li>Have inventory for the product at one or more physical stores tied to the merchant's account. <p>Sellers can use the <b>createInventoryLocaion</b> method in the Inventory API to associate physical stores to their account and they can then can add inventory to specific store locations.</p></li><li>Set an immediate payment requirement on the item. The immediate payment feature requires the seller to: <ul><li>Set the <b>immediatePay</b> flag in the payment policy to 'true'.</li><li>Have a valid store location with a complete street address.</li></ul></li></ul><p>When a merchant successfully lists an item with Click and Collect, prospective buyers within a reasonable distance from one of the merchant's stores (that has stock available) will see the "Available for Click and Collect" option on the listing, along with information on the closest store that has the item.</p><b>Default</b>: false
	Shippingoptions []ShippingOption `json:"shippingOptions,omitempty"` // This array is used to provide detailed information on the domestic and international shipping options available for the policy. <br /><br />A separate <b>ShippingOption</b> object is required for domestic shipping service options and for international shipping service options (if the seller ships to international locations). <ul><li>The <b>optionType</b> field is used to indicate whether the <b>ShippingOption</b> object applies to domestic or international shipping, and the <b>costType</b> field is used to indicate whether flat-rate shipping or calculated shipping will be used.</li> <li>The <b>rateTableId</b> field can be used to associate a defined shipping rate table to the policy, and the <b>packageHandlingCost</b> container can be used to set a handling charge for the policy.</li></ul> <p>A separate <b>ShippingServices</b> object will be used to specify cost and other details for every available domestic and international shipping service option. </p>
}

// InternationalReturnOverrideType represents the InternationalReturnOverrideType schema from the OpenAPI specification
type InternationalReturnOverrideType struct {
	Returnmethod string `json:"returnMethod,omitempty"` // This field sets/indicates if the seller offers replacement items to the buyer in the case of an international return. The buyer must be willing to accept a replacement item; otherwise, the seller will need to issue a refund for a return. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum'>eBay API documentation</a>
	Returnperiod TimeDuration `json:"returnPeriod,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Returnshippingcostpayer string `json:"returnShippingCostPayer,omitempty"` // This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either <code>BUYER</code> or <code>SELLER</code>. <br/><br/>Depending on the return policy and specifics of the return, either the buyer or the seller can be responsible for the return shipping costs. Note that the seller is always responsible for return shipping costs for 'significantly not as described' (SNAD) issues. <br/><br/>This field is conditionally required if the <b>internationalOverride.returnsAccepted</b> field is set to <code>true</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum'>eBay API documentation</a>
	Returnsaccepted bool `json:"returnsAccepted,omitempty"` // If set to <code>true</code>, the seller accepts international returns. If set to <code>false</code>, the seller does not accept international returns. <br/><br/>This field is conditionally required if the seller chooses to have a separate international return policy.
}

// SetPaymentPolicyResponse represents the SetPaymentPolicyResponse schema from the OpenAPI specification
type SetPaymentPolicyResponse struct {
	Warnings []Error `json:"warnings,omitempty"` // An array of one or more errors or warnings that were generated during the processing of the request. If there were no issues with the request, this array will return empty.
	Name string `json:"name,omitempty"` // A seller-defined name for this payment business policy. Names must be unique for policies assigned to the same marketplace.<br /><br /><b>Max length:</b> 64
	Paymentmethods []PaymentMethod `json:"paymentMethods,omitempty"` // This array shows the available payment methods that the seller has set for the payment business policy.<br /><br />Sellers do not have to specify any electronic payment methods for listings, so this array will often be returned empty unless the payment business policy is intended for motor vehicle listings or other items in categories where offline payments are required or supported.
	Paymentpolicyid string `json:"paymentPolicyId,omitempty"` // A unique eBay-assigned ID for a payment business policy. This ID is generated when the policy is created.
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates whether the payment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Deposit Deposit `json:"deposit,omitempty"` // This type is used to specify/indicate that an initial deposit is required for a motor vehicle listing.
	Fullpaymentduein TimeDuration `json:"fullPaymentDueIn,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this payment business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Paymentinstructions string `json:"paymentInstructions,omitempty"` // <p class="tablenote"><b>Note:</b> NO LONGER SUPPORTED. Although this field may be returned for some older payment business policies, payment instructions are no longer supported by payment business policies. If this field is returned, it can be ignored and these payment instructions will not appear in any listings that use the corresponding business policy.</p>A free-form string field that allows sellers to add detailed payment instructions to their listings.
	Description string `json:"description,omitempty"` // A seller-defined description of the payment business policy. This description is only for the seller's use, and is not exposed on any eBay pages. This field is returned if set for the policy. <br/><br/><b>Max length</b>: 250
	Immediatepay bool `json:"immediatePay,omitempty"` // The value returned in this field will reflect the value set by the seller in the <b>immediatePay</b> request field. A value of <code>true</code> indicates that immediate payment is required from the buyer for: <ul><li>A fixed-price item</li><li>An auction item where the buyer is using the 'Buy it Now' option</li><li>A deposit for a motor vehicle listing</li></ul><br />It is possible for the seller to set this field as <code>true</code> in the payment business policy, but it will not apply in some scenarios. For example, immediate payment is not applicable for auction listings that have a winning bidder, for buyer purchases that involve the Best Offer feature, or for transactions that happen offline between the buyer and seller.
}

// SellingPrivileges represents the SellingPrivileges schema from the OpenAPI specification
type SellingPrivileges struct {
	Sellerregistrationcompleted bool `json:"sellerRegistrationCompleted,omitempty"` // If this field is returned as <code>true</code>, the seller's registration is completed. If this field is returned as <code>false</code>, the registration process is not complete.
	Sellinglimit SellingLimit `json:"sellingLimit,omitempty"` // Type used by the <b>sellingLimit</b> container, a container that lists the monthly cap for the quantity of items sold and total sales amount allowed for the seller's account.
}

// ShippingService represents the ShippingService schema from the OpenAPI specification
type ShippingService struct {
	Shiptolocations RegionSet `json:"shipToLocations,omitempty"` // This type consists of the <b>regionIncluded</b> and <b>regionExcluded</b> arrays, which indicate the areas to where the seller does and doesn't ship.
	Sortorder int `json:"sortOrder,omitempty"` // The integer value set in this field controls the order of the corresponding domestic or international shipping service option in the View Item and Checkout pages. <br/><br/>Sellers can specify up to four domestic shipping services (in four separate <b>shippingService</b> containers), so valid values are 1, 2, 3, and 4. A shipping service option with a <b>sortOrder</b> value of <code>1</code> appears at the top of View Item and Checkout pages. Conversely, a shipping service option with a <b>sortOrder</b> value of <code>1</code> appears at the bottom of the list. <br/><br/>Sellers can specify up to five international shipping services (in five separate <b>shippingService</b> containers), so valid values for international shipping services are 1, 2, 3, 4, and 5. Similarly to domestic shipping service options, the <b>sortOrder</b> value of a international shipping service option controls the placement of that shipping service option in the View Item and Checkout pages. <br/><br/>If the <b>sortOrder</b> field is not supplied, the order of domestic and international shipping service options is determined by the order in which they are listed in the API call. <br/><br/><b>Min</b>: 1. <b>Max</b>: 4 (for domestic shipping service) or 5 (for international shipping service).
	Shippingcost Amount `json:"shippingCost,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Shippingservicecode string `json:"shippingServiceCode,omitempty"` // This field sets/indicates the domestic or international shipping service option, such as <code>USPSPriority</code>, <code>FedEx2Day</code>, or <code>UPS3rdDay</code>. Although this field uses the <b>string</b> type, the seller must pass in a pre-defined enumeration value here. <br /><br />For a full list of shipping service option enum values for a specified eBay marketplace, the <b>GeteBayDetails</b> call of the <b>Trading API</b> can be used, and the <b>DetailName</b> field's value should be set to <code>ShippingServiceDetails</code>. <br /><br />The enum values for each shipping service option can be found in each <b>ShippingServiceDetails.ShippingService</b> field in the response payload. The seller must make sure that the shipping service option is still valid, which is indicated by a <code>true</code> value in the corresponding <b>ValidForSellingFlow</b> boolean field. International shipping service options are typically returned at the top of the response payload, and are indicated by an <b>InternationalService</b> boolean field that reads <code>true</code>. <br /><br />The <b>InternationalService</b> boolean field is not returned at all for domestic shipping service options. <br/><br/> This field is required for every specified shipping service option.<br/><br/>This field is returned if set.
	Additionalshippingcost Amount `json:"additionalShippingCost,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Buyerresponsibleforshipping bool `json:"buyerResponsibleForShipping,omitempty"` // This field should be included and set to <code>true</code> for a motor vehicle listing if it will be the buyer's responsibility to arrange for shipment of a purchased motor vehicle after full payment is made. <br /><br />This field is only applicable to motor vehicle listings. In the majority of motor vehicle listings, the seller does make the buyer responsible for pickup or shipment of the vehicle. <br/><br/>This field is returned if set.<br/><br/><b>Default</b>: false
	Freeshipping bool `json:"freeShipping,omitempty"` // This field is included and set to <code>true</code> if the seller offers a free shipping option to the buyer. <br /><br />This field can only be included and set to <code>true</code> for the first domestic shipping service option specified in the <b>shippingServices</b> container (it is ignored if set for subsequent shipping services or for any international shipping service option). <br /><br />The first specified shipping service option has a <b>sortOrder</b> value of <code>1</code> or if the <b>sortOrderId</b> field is not used, it is the shipping service option that's specified first in the <b>shippingServices</b> container.<br/><br/>This container is returned if set.
	Shippingcarriercode string `json:"shippingCarrierCode,omitempty"` // This field sets/indicates the shipping carrier, such as <code>USPS</code>, <code>FedEx</code>, or <code>UPS</code>. Although this field uses the <b>string</b> type, the seller must pass in a pre-defined enumeration value here. <br /><br />For a full list of shipping carrier enum values for a specified eBay marketplace, the <b>GeteBayDetails</b> call of the <b>Trading API</b> can be used, and the <b>DetailName</b> field's value should be set to <code>ShippingCarrierDetails</code>. The enum values for each shipping carriers can be found in each <b>ShippingCarrierDetails.ShippingCarrier</b> field in the response payload.<br/><br/> This field is actually optional, as the shipping carrier is also tied into the <b>shippingServiceCode</b> enum value, and that field is required for every specified shipping service option.<br/><br/>This field is returned if set.
	Buyerresponsibleforpickup bool `json:"buyerResponsibleForPickup,omitempty"` // This field should be included and set to <code>true</code> for a motor vehicle listing if it will be the buyer's responsibility to pick up the purchased motor vehicle after full payment is made. <br /><br />This field is only applicable to motor vehicle listings. In the majority of motor vehicle listings, the seller does make the buyer responsible for pickup or shipment of the vehicle. <br/><br/>This field is returned if set.<br/><br/><b>Default</b>: false
	Surcharge Amount `json:"surcharge,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
	Cashondeliveryfee Amount `json:"cashOnDeliveryFee,omitempty"` // A complex type that describes the value of a monetary amount as represented by a global currency. When passing in an amount in a request payload, both <b>currency</b> and <b>value</b> fields are required, and both fields are also always returned for an amount in a response field.
}

// SetFulfillmentPolicyResponse represents the SetFulfillmentPolicyResponse schema from the OpenAPI specification
type SetFulfillmentPolicyResponse struct {
	Handlingtime TimeDuration `json:"handlingTime,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Pickupdropoff bool `json:"pickupDropOff,omitempty"` // If returned as <code>true</code>, the seller offers the "Click and Collect" option. <br/><br/>Currently, "Click and Collect" is available only to large retail merchants the eBay AU and UK marketplaces.
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates whether the fulfillment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Freightshipping bool `json:"freightShipping,omitempty"` // If returned as <code>true</code>, the seller offers freight shipping. Freight shipping can be used for large items over 150 lbs.
	Localpickup bool `json:"localPickup,omitempty"` // If returned as <code>true</code>, local pickup is available for this policy.
	Shiptolocations RegionSet `json:"shipToLocations,omitempty"` // This type consists of the <b>regionIncluded</b> and <b>regionExcluded</b> arrays, which indicate the areas to where the seller does and doesn't ship.
	Description string `json:"description,omitempty"` // A seller-defined description of the fulfillment policy. This description is only for the seller's use, and is not exposed on any eBay pages. This field is returned if set for the policy. <br/><br/><b>Max length</b>: 250
	Warnings []Error `json:"warnings,omitempty"` // An array of one or more errors or warnings that were generated during the processing of the request. If there were no issues with the request, this array will return empty.
	Globalshipping bool `json:"globalShipping,omitempty"` // If returned as <code>true</code>, the eBay Global Shipping Program will be used by the seller to ship items to international locations.<br /><br /><span class="tablenote"><b>Note</b>: On the US marketplace, the <em><b>Global Shipping Program</b></em> is scheduled to be replaced by a new intermediated international shipping program called <em><b>eBay International Shipping</b></em>. US sellers who are opted in to the Global Shipping Program will be automatically opted in to eBay International Shipping when it becomes available to them. All US sellers will be migrated by March 31, 2023. <br /><br />eBay International Shipping is an account level setting, and no field needs to be set in a Fulfillment business policy to enable it. As long as the US seller's account is opted in to eBay International Shipping, this shipping option will be enabled automatically for all listings where international shipping is available. <br /><br />A US seller who is opted in to eBay International Shipping can also specify individual international shipping service options for a Fulfillment business policy.</span>
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this fulfillment business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Name string `json:"name,omitempty"` // A seller-defined name for this fulfillment business policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64
	Shippingoptions []ShippingOption `json:"shippingOptions,omitempty"` // This array is used to provide detailed information on the domestic and international shipping options available for the policy. A separate <b>ShippingOption</b> object covers domestic shipping service options and international shipping service options (if the seller ships to international locations). <br /><br />The <b>optionType</b> field indicates whether the <b>ShippingOption</b> object applies to domestic or international shipping, and the <b>costType</b> field indicates whether flat-rate shipping or calculated shipping will be used. <p>A separate <b>ShippingServices</b> object is used to specify cost and other details for every available domestic and international shipping service option. </p>
	Fulfillmentpolicyid string `json:"fulfillmentPolicyId,omitempty"` // A unique eBay-assigned ID for a fulfillment business policy. This ID is generated when the policy is created.
}

// SellerEligibilityMultiProgramResponse represents the SellerEligibilityMultiProgramResponse schema from the OpenAPI specification
type SellerEligibilityMultiProgramResponse struct {
	Advertisingeligibility []SellerEligibilityResponse `json:"advertisingEligibility,omitempty"` // An array of response fields that define the seller eligibility for eBay adverstising programs.
}

// PaymentPolicy represents the PaymentPolicy schema from the OpenAPI specification
type PaymentPolicy struct {
	Paymentpolicyid string `json:"paymentPolicyId,omitempty"` // A unique eBay-assigned ID for a payment business policy. This ID is generated when the policy is created.
	Name string `json:"name,omitempty"` // A seller-defined name for this fulfillment policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64
	Description string `json:"description,omitempty"` // A seller-defined description of the payment policy. This description is only for the seller's use, and is not exposed on any eBay pages. <br/><br/><b>Max length</b>: 250
	Fullpaymentduein TimeDuration `json:"fullPaymentDueIn,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which the payment business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Paymentinstructions string `json:"paymentInstructions,omitempty"` // Although this field may be returned for some older payment business policies, payment instructions are no longer supported by payment business policies. If this field is returned, it can be ignored and these payment instructions will not appear in any listings that use the corresponding business policy. <br/><br/><b>Max length</b>: 1000
	Paymentmethods []PaymentMethod `json:"paymentMethods,omitempty"` // This container is returned to show the payment methods that are accepted for the payment business policy. <br><br>Sellers do not have to specify any electronic payment methods for listings, so this array will often be returned empty unless the payment business policy is intended for motor vehicle listings or other items in categories where offline payments are required or supported.
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container indicates whether the fulfillment policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Deposit Deposit `json:"deposit,omitempty"` // This type is used to specify/indicate that an initial deposit is required for a motor vehicle listing.
	Immediatepay bool `json:"immediatePay,omitempty"` // If this field is returned as <code>true</code>, immediate payment is required from the buyer for: <ul><li>A fixed-price item</li><li>An auction item where the buyer uses the 'Buy it Now' option</li><li>A deposit for a motor vehicle listing</li></ul><br />It is possible for the seller to set this field as <code>true</code> in the payment business policy, but it will not apply in some scenarios. For example, immediate payment is not applicable for auction listings that have a winning bidder, for buyer purchases that involve the Best Offer feature, or for transactions that happen offline between the buyer and seller.
}

// SetReturnPolicyResponse represents the SetReturnPolicyResponse schema from the OpenAPI specification
type SetReturnPolicyResponse struct {
	Returnmethod string `json:"returnMethod,omitempty"` // This field will be returned if the seller is willing and able to offer a replacement item as an alternative to 'Money Back'. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum'>eBay API documentation</a>
	Warnings []Error `json:"warnings,omitempty"` // An array of one or more errors or warnings that were generated during the processing of the request. If there were no issues with the request, this array will return empty.
	Refundmethod string `json:"refundMethod,omitempty"` // If a seller indicates that they will accept buyer returns, this value will be <code>MONEY_BACK</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:RefundMethodEnum'>eBay API documentation</a>
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this return business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Restockingfeepercentage string `json:"restockingFeePercentage,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer allows sellers to charge a restocking fee for buyer remorse returns.</p>
	Returnshippingcostpayer string `json:"returnShippingCostPayer,omitempty"` // This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either <code>BUYER</code> or <code>SELLER</code>. <br/><br/>Note that the seller is always responsible for return shipping costs for SNAD-related issues. <br/><br/>This container will be returned unless the business policy states that the seller does not accept returns. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum'>eBay API documentation</a>
	Returnsaccepted bool `json:"returnsAccepted,omitempty"` // If set to <code>true</code>, the seller accepts returns. If set to <code>false</code>, this field indicates that the seller does not accept returns.
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This field always returns <code>ALL_EXCLUDING_MOTORS_VEHICLES</code> for return business policies, since return business policies are not applicable to motor vehicle listings.
	Returnperiod TimeDuration `json:"returnPeriod,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Extendedholidayreturnsoffered bool `json:"extendedHolidayReturnsOffered,omitempty"` // <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is deprecated, since eBay no longer supports extended holiday returns. This field should no longer be returned.</p>
	Description string `json:"description,omitempty"` // A seller-defined description of the return business policy. This description is only for the seller's use, and is not exposed on any eBay pages. This field is returned if set for the policy. <br/><br/><b>Max length</b>: 250
	Returninstructions string `json:"returnInstructions,omitempty"` // This text-based field provides more details on seller-specified return instructions. <p class="tablenote"><span style="color: #dd1e31;"><b>Important!</b></span> This field is no longer supported on many eBay marketplaces. To see if a marketplace and eBay category does support this field, call <a href="/api-docs/sell/metadata/resources/marketplace/methods/getReturnPolicies">getReturnPolicies</a> method of the <b>Metadata API</b>. Then you will look for the <b>policyDescriptionEnabled</b> field with a value of <code>true</code> for the eBay category.</span></p><br/><b>Max length</b>: 5000 (8000 for DE)
	Name string `json:"name,omitempty"` // A seller-defined name for this return business policy. Names must be unique for policies assigned to the same marketplace.<br /><br /><b>Max length:</b> 64
	Internationaloverride InternationalReturnOverrideType `json:"internationalOverride,omitempty"` // This type defines the fields for a seller's international return policy. Sellers have the ability to set separate domestic and international return policies, but if an international return policy is not set, the same return policy settings specified for the domestic return policy are also used for returns for international buyers.
	Returnpolicyid string `json:"returnPolicyId,omitempty"` // A unique eBay-assigned ID for a return business policy. This ID is generated when the policy is created.
}

// CustomPolicy represents the CustomPolicy schema from the OpenAPI specification
type CustomPolicy struct {
	Custompolicyid string `json:"customPolicyId,omitempty"` // The unique custom policy identifier for a policy.<br/><br/><span class="tablenote"><strong>Note:</strong> This value is automatically assigned by the system when the policy is created.</span>
	Description string `json:"description,omitempty"` // Details of the seller's specific policy and terms associated with the policy. Buyers access this information from the View Item page for items to which the policy has been applied.<br/><br/><b>Max length:</b> 15,000
	Label string `json:"label,omitempty"` // Customer-facing label shown on View Item pages for items to which the policy applies. This seller-defined string is displayed as a system-generated hyperlink pointing to detailed policy information.<br/><br/><b>Max length:</b> 65
	Name string `json:"name,omitempty"` // The seller-defined name for the custom policy. Names must be unique for policies assigned to the same seller, policy type, and eBay marketplace.<br /><span class="tablenote"><strong>Note:</strong> This field is visible only to the seller. </span><br/><br/><b>Max length:</b> 65
	Policytype string `json:"policyType,omitempty"` // Specifies the type of Custom Policy. <br/><br/>Two Custom Policy types are supported: <ul><li>Product Compliance (PRODUCT_COMPLIANCE)</li> <li>Takeback (TAKE_BACK)</li></ul> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:CustomPolicyTypeEnum'>eBay API documentation</a>
}

// Error represents the Error schema from the OpenAPI specification
type Error struct {
	Errorid int `json:"errorId,omitempty"` // A positive integer that uniquely identifies the specific error condition that occurred. Your application can use error codes as identifiers in your customized error-handling algorithms.
	Inputrefids []string `json:"inputRefIds,omitempty"` // Identifies specific request elements associated with the error, if any. inputRefId's response is format specific. For JSON, use <i>JSONPath</i> notation.
	Longmessage string `json:"longMessage,omitempty"` // A more detailed explanation of the error than given in the <code>message</code> error field.
	Parameters []ErrorParameter `json:"parameters,omitempty"` // This optional list of name/value pairs that contain context-specific <code>ErrorParameter</code> objects, with each item in the list being a parameter (or input field name) that caused an error condition. Each <code>ErrorParameter</code> object consists of two fields, a <code>name</code> and a <code>value</code>.
	Message string `json:"message,omitempty"` // Information on how to correct the problem, in the end user's terms and language where applicable. Its value is at most 50 characters long. If applicable, the value is localized in the end user's requested locale.
	Outputrefids []string `json:"outputRefIds,omitempty"` // Identifies specific response elements associated with the error, if any. Path format is the same as <code>inputRefId</code>.
	Subdomain string `json:"subdomain,omitempty"` // If present, indicates the subsystem in which the error occurred.
	Category string `json:"category,omitempty"` // The category type for this error or warning. It is a string that can have one of three values:<ul><li><code>Application</code>: Indicates an exception or error occurred in the application code or at runtime. Examples include catching an exception in a service's business logic, system failures, or request errors from a dependency.</li><li><code>Business</code>: Used when your service or a dependent service refused to continue processing on the resource because of a business rule violation such as "Seller does not ship item to Antarctica" or "Buyer ineligible to purchase an alcoholic item". Business errors are not syntactical input errors.</li><li><code>Request</code>: Used when there is anything wrong with the request, such as authentication, syntactical errors, rate limiting or missing headers, bad HTTP header values, and so on.</li></ul>
	Domain string `json:"domain,omitempty"` // Name of the domain ,or primary system, of the service or application where the error occurred.
}

// ErrorParameter represents the ErrorParameter schema from the OpenAPI specification
type ErrorParameter struct {
	Value string `json:"value,omitempty"` // The value of the parameter that caused the error.
	Name string `json:"name,omitempty"` // Name of the parameter that caused the error.
}

// KycCheck represents the KycCheck schema from the OpenAPI specification
type KycCheck struct {
	Datarequired string `json:"dataRequired,omitempty"` // The enumeration value returned in this field categorizes the type of details needed for the KYC check. More information about the check is shown in the <b>detailMessage</b> and other applicable, corresponding fields. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/kyc:DetailsType'>eBay API documentation</a>
	Detailmessage string `json:"detailMessage,omitempty"` // This field gives a detailed message about what is required from the seller. An example might be, '<code>Please upload a bank document by 2020-08-01 to get your account back in good standing.</code>'.
	Duedate string `json:"dueDate,omitempty"` // The timestamp in this field indicates the date by which the seller should resolve the KYC requirement.<br><br>The timestamp in this field uses the UTC date and time format described in the <a href="https://www.iso.org/iso-8601-date-and-time-format.html" target="_blank">ISO 8601 Standard</a>. See below for this format and an example: <br><br><i>MM-DD-YYYY HH:MM:SS</i><br/><code>06-05-2020 10:34:18</code>
	Remedyurl string `json:"remedyUrl,omitempty"` // If applicable and available, a URL will be returned in this field, and the link will take the seller to an eBay page where they can provide the requested information.
	Alert string `json:"alert,omitempty"` // This field gives a short summary of what is required from the seller. An example might be, '<code>Upload bank document now.</code>'. The <b>detailMessage</b> field will often provide more details on what is required of the seller.
}

// Subscription represents the Subscription schema from the OpenAPI specification
type Subscription struct {
	Marketplaceid string `json:"marketplaceId,omitempty"` // The marketplace with which the subscription is associated. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Subscriptionid string `json:"subscriptionId,omitempty"` // The subscription ID.
	Subscriptionlevel string `json:"subscriptionLevel,omitempty"` // The subscription level. For example, subscription levels for an eBay store include Starter, Basic, Featured, Anchor, and Enterprise levels.
	Subscriptiontype string `json:"subscriptionType,omitempty"` // The kind of entity with which the subscription is associated, such as an eBay store. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:SubscriptionTypeEnum'>eBay API documentation</a>
	Term TimeDuration `json:"term,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
}

// FulfillmentPolicyResponse represents the FulfillmentPolicyResponse schema from the OpenAPI specification
type FulfillmentPolicyResponse struct {
	Total int `json:"total,omitempty"` // The total number of fulfillment policies retrieved in the result set. <br/><br/>If no fulfillment policies are defined for the specified marketplace, this field is returned with a value of <code>0</code>.
	Fulfillmentpolicies []FulfillmentPolicy `json:"fulfillmentPolicies,omitempty"` // A list of all of the seller's fulfillment policies defined for the specified marketplace. This array will be returned as empty if no fulfillment policies are defined for the specified marketplace.
	Href string `json:"href,omitempty"` // This field is for future use.
	Limit int `json:"limit,omitempty"` // This field is for future use.
	Next string `json:"next,omitempty"` // This field is for future use.
	Offset int `json:"offset,omitempty"` // This field is for future use.
	Prev string `json:"prev,omitempty"` // This field is for future use.
}

// PaymentPolicyRequest represents the PaymentPolicyRequest schema from the OpenAPI specification
type PaymentPolicyRequest struct {
	Name string `json:"name,omitempty"` // A seller-defined name for this payment business policy. Names must be unique for policies assigned to the same marketplace.<br /><br /><b>Max length:</b> 64
	Deposit Deposit `json:"deposit,omitempty"` // This type is used to specify/indicate that an initial deposit is required for a motor vehicle listing.
	Fullpaymentduein TimeDuration `json:"fullPaymentDueIn,omitempty"` // A type used to specify a period of time using a specified time-measurement unit. Payment, return, and fulfillment business policies all use this type to specify time windows.<br/><br/>Whenever a container that uses this type is used in a request, both of these fields are required. Similarly, whenever a container that uses this type is returned in a response, both of these fields are always returned.
	Immediatepay bool `json:"immediatePay,omitempty"` // This field should be included and set to <code>true</code> if the seller wants to require immediate payment from the buyer for: <ul><li>A fixed-price item</li><li>An auction item where the buyer is using the 'Buy it Now' option</li><li>A deposit for a motor vehicle listing</li></ul><br /><b>Default:</b> False
	Marketplaceid string `json:"marketplaceId,omitempty"` // The ID of the eBay marketplace to which this payment business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>
	Paymentinstructions string `json:"paymentInstructions,omitempty"` // <p class="tablenote"><b>Note:</b> DO NOT USE THIS FIELD. Payment instructions are no longer supported by payment business policies.</p>A free-form string field that allows sellers to add detailed payment instructions to their listings.
	Paymentmethods []PaymentMethod `json:"paymentMethods,omitempty"` // <p class="tablenote"><b>Note:</b> This field applies only when the seller needs to specify one or more offline payment methods. eBay now manages the electronic payment options available to buyers to pay for the item.</p>This array is used to specify one or more offline payment methods that will be accepted for payment that occurs off of eBay's platform.
	Categorytypes []CategoryType `json:"categoryTypes,omitempty"` // This container is used to specify whether the payment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
	Description string `json:"description,omitempty"` // A seller-defined description of the payment business policy. This description is only for the seller's use, and is not exposed on any eBay pages. <br/><br/><b>Max length</b>: 250
}

// Program represents the Program schema from the OpenAPI specification
type Program struct {
	Programtype string `json:"programType,omitempty"` // A seller program in to which a seller can opt-in. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ProgramTypeEnum'>eBay API documentation</a>
}
